---
- name: test register
  hosts: node1.example.com
  tasks:
    - shell: cat /etc/passwd
      register: passwd_contents
    - debug:
        var: passwd_contents
    - debug: 
        msg: echo "passwd contains user jenkins"
      when: passwd_contents.stdout.find('jenkins') != -1
