---
- name: when demo
  hosts: node1.example.com
  vars:
    supported_distros:
      - CentOS
      - RedHat
      - Fedora
  tasks:
    - name: install RH family specific packages
      yum:
        name: httpd
        state: present
      when: ansible_distribution in supported_distros 


