---
- name: demonstrating failed_when
  hosts: node1.example.com
  tasks: 
    - name: run a script
      command: echo hello world
      ignore_errors: no
      register: command_result
      failed_when: "'world' in command_result.stdout"
    - name: see if we get here
      debug:
        msg: hello
