---
- name: show the fail module
  hosts: node1.example.com
  tasks:
  - name: do something impossible
    lvol:
      lv: lvnothing
      vg: vgnothing
      size: 1G
    register: command_result
    ignore_errors: yes
  - name: show command_result errors
    debug:
      var: command_result
  - name: print nice error message after failure
    fail:
      msg: volume group doesnt exist
    when: "'Volume group vgnothing does not exist.' in command_result.msg"
